[package]
name = "hello-rust"
version = "0.1.0"
edition = "2018"

[dependencies]
env_logger = "0.9.0"
launchdarkly-server-sdk = { version = "1.0.0-beta.1" }
tokio = { version = "1.15.0", features = ["rt", "macros"] }

[features]
